export const fakeFoods = [
    {
        name: 'Pizza',
        img_url: '/assets/images/pizza.jpg',
        category: 'Pizza',
        desc: 'Lorem ipsum es int at',
        actual_price: '$3.52',
        discounted_price: '$1.50',
        discount_available: 1,
        variants: [
            { variant: 'small', actual_price: '$5.00', discounted_price: '$3.50' },
            { variant: 'medium', actual_price: '$7.00', discounted_price: '$4.50' },
            { variant: 'big', actual_price: '$9.00', discounted_price: '$5.50' },
        ],
    },
    {
        name: 'Kebab',
        img_url: '/assets/images/kebab.jpg',
        category: 'Kebab',
        desc: 'Lorem ipsum es int at',
        actual_price: '$4.48',
        discounted_price: '$1.32',
        discount_available: 0,
        variants: [
            { variant: 'small', actual_price: '$5.00', discounted_price: '$3.50' },
            { variant: 'medium', actual_price: '$7.00', discounted_price: '$4.50' },
            { variant: 'small', actual_price: '$9.00', discounted_price: '$5.50' },
        ],
    },
    {
        name: 'Biriyani',
        img_url: '/assets/images/biriyani.jpg',
        category: 'Biriyani',
        desc: 'Lorem ipsum es int atawdadasdadwadw',
        actual_price: '$2.14',
        discounted_price: '$1.50',
        discount_available: 0,
        variants: [
            { variant: 'small', actual_price: '$5.00', discounted_price: '$3.50' },
            { variant: 'medium', actual_price: '$7.00', discounted_price: '$4.50' },
            { variant: 'small', actual_price: '$9.00', discounted_price: '$5.50' },
        ],
    },
    {
        name: 'Hotdog',
        img_url: '/assets/images/hotdog.jpg',
        category: 'Hotdog',
        desc: 'Lorem ipsum es int atasdasdasdasdasd',
        actual_price: '$1.52',
        discounted_price: '$1.12',
        discount_available: 0,
        variants: [
            { variant: 'small', actual_price: '$5.00', discounted_price: '$3.50' },
            { variant: 'medium', actual_price: '$7.00', discounted_price: '$4.50' },
            { variant: 'small', actual_price: '$9.00', discounted_price: '$5.50' },
        ],
    },
    {
        name: 'Burger',
        img_url: '/assets/images/burger.jpg',
        category: 'Burger',
        desc: 'Lorem ipsum es int atsacasccccccccccccccccccccccccccaaaaaawwwwww',
        actual_price: '$7.52',
        discounted_price: '$2.50',
        discount_available: 0,
        variants: [
            { variant: 'small', actual_price: '$5.00', discounted_price: '$3.50' },
            { variant: 'medium', actual_price: '$7.00', discounted_price: '$4.50' },
            { variant: 'small', actual_price: '$9.00', discounted_price: '$5.50' },
        ],
    },
];
